---
name: up
on:
  push:
    branches:
      - master
    tags:
      - '*'
concurrency:
  group: up-${{ github.ref }}
  cancel-in-progress: true
jobs:
  up:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - run: |-
          git fetch --tags --force && \
          latest=$(git tag --sort=creatordate | tail -1) && \
          sed -E -i "s/<version>[^<]+/<version>${latest}/g" README.md
      - uses: peter-evans/create-pull-request@v6
        with:
          branch: version-up
          commit-message: 'chore: new version in README'
          delete-branch: true
          title: 'chore: New version in README'
          assignees: volodya-lombrozo
          base: master